Resources:

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: miKeyPair                    
      ImageId: ami-0049736975ba478c0        # Cogemos la AMI
      InstanceType: t3.micro                # Compatible con Free Tier
      SecurityGroupIds:
        - !Ref secGroupName                 # SG con puertos 22 y 80
      SubnetId: !Ref subnetName             # EC2 en subnet pública
      IamInstanceProfile: !Ref myInstanceProfile   # Permisos para CloudWatch

      UserData:                             # Script que instala la API REST 
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y python3 pip amazon-cloudwatch-agent

          pip install flask psutil

          cat <<EOF > /home/ec2-user/app.py
          from flask import Flask, jsonify
          import psutil

          app = Flask(__name__)

          @app.route("/status")
          def status():
              return jsonify({"status": "ok"})

          @app.route("/metrics")
          def metrics():
              return jsonify({
                  "cpu": psutil.cpu_percent(),
                  "memory": psutil.virtual_memory().percent,
                  "disk": psutil.disk_usage('/').percent
              })

          @app.route("/hello")
          def hello():
              return "Hola desde Maniac API!"

          app.run(host="0.0.0.0", port=80)
          EOF

          python3 /home/ec2-user/app.py &   # Arranca la API

      Tags:
        - Key: Name
          Value: Maniac-EC2


  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG del proyecto Maniac
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp                   # SSH
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp                   # API REST en puerto 80
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1                    # Todo tráfico saliente
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Maniac-SG


  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: manIaC-VPC


  subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: eu-west-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: manIaC-Subnet
  subnetName2:
    Type: AWS::EC2::Subnet    # Subred adicional para el ALB
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: eu-west-1b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: manIaC-Subnet-2



  igwName:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: manIaC-IGW


  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref igwName


  routeTableName:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: manIaC-RT


  routeToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref routeTableName
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref igwName


  associateSubnetRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnetName
      RouteTableId: !Ref routeTableName

  associateSubnetRouteTable2:  # MUY IMPORTANTE OTRA SUBNET PARA EL ALB, SINO NO FUNCIONA
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnetName2
      RouteTableId: !Ref routeTableName



  myEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy


  myInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref myEC2Role


  maniacALBSG:  
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG para el ALB
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Maniac-ALB-SG


  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref myVPC
      TargetType: instance
      Port: 80
      Protocol: HTTP
      HealthCheckPath: /status
      Targets:
        - Id: !Ref myEC2Instance
          Port: 80


  myALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Name: manIaC-ALB
      Subnets:
        - !Ref subnetName
        - !Ref subnetName2  # IMPORTANTE REFERENCIAR LA OTRA SUBNET PARA EL ALB, SINO NO FUNCIONA
      SecurityGroups:
        - !Ref maniacALBSG
      Tags:
        - Key: Name
          Value: manIaC-ALB


  myALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref myALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup