Resources:

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: miKeyPair
      ImageId: ami-0049736975ba478c0
      InstanceType: t3.micro
      SecurityGroupIds:
        - !Ref secGroupName
      SubnetId: !Ref subnetName
      IamInstanceProfile: !Ref myInstanceProfile

      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y python3 pip amazon-cloudwatch-agent

          pip install flask psutil

          cat <<EOF > /home/ec2-user/app.py
          from flask import Flask, jsonify
          import psutil

          app = Flask(__name__)

          @app.route("/status")
          def status():
              return jsonify({"status": "ok"})

          @app.route("/metrics")
          def metrics():
              return jsonify({
                  "cpu": psutil.cpu_percent(),
                  "memory": psutil.virtual_memory().percent,
                  "disk": psutil.disk_usage('/').percent
              })

          @app.route("/hello")
          def hello():
              return "Hola desde Maniac API!"

          app.run(host="0.0.0.0", port=80)
          EOF

          python3 /home/ec2-user/app.py &
      Tags:
        - Key: Name
          Value: Maniac-EC2


  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG del proyecto Maniac
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Maniac-SG


  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: manIaC-VPC


  subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: eu-west-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: manIaC-Subnet

  subnetName2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: eu-west-1b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: manIaC-Subnet-2


  igwName:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: manIaC-IGW


  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref igwName


  routeTableName:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: manIaC-RT


  routeToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref routeTableName
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref igwName


  associateSubnetRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnetName
      RouteTableId: !Ref routeTableName

  associateSubnetRouteTable2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnetName2
      RouteTableId: !Ref routeTableName


  myEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy


  myInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref myEC2Role
  
